export const Constants = {
  LANGUAGE: 'lang',
  VI: 'vi',
  EN: 'en',
  JP: 'jp',
  TOKEN: 'token',
  USER_ID: 'userId',
  DEFAULT: 'default',
  REQUESTED: 1,
  FOLOWING: 2,
  INVITE: 3,
  TEAM_ADMIN: 'TEAM_ADMIN',
  TEAM_MEMBER: 'TEAM_MEMBER',
  PRIVACY: 'PRIVACY',
  ACTIVE_TEAM: 'activeTeam',
  STATUS_PAID_DONE: 9,
  STATUS_PAID_WAITING: 8,
  STATUS_PAID_NOT_PAID: 7,
};
