import {StyleSheet, Dimensions} from 'react-native';
import {Colors, ApplicationStyles, Helpers} from '../../Theme';
const {width} = Dimensions.get('window');

export default StyleSheet.create({
  view: {
    ...ApplicationStyles.backgroundView,
    paddingBottom: 20,
  },
  headerRight: {
    fontSize: 15,
    ...ApplicationStyles.fontMPLUS1pMedium,
    color: Colors.white,
  },
  viewContainer: {
    ...Helpers.fullSize,
    ...ApplicationStyles.paddingHorizontalView,
  },
  viewChangeAvatar: {
    backgroundColor: Colors.black,
    opacity: 0.36,
    width: 116,
    height: 58,
    position: 'absolute',
    bottom: 0,
    borderBottomLeftRadius: 65,
    borderBottomRightRadius: 65,
    justifyContent: 'center',
    alignItems: 'center',
    overflow: 'hidden',
  },
  viewIcon: {
    width: 116,
    height: 58,
    position: 'absolute',
    bottom: 0,
    justifyContent: 'center',
    alignItems: 'center',
  },
  viewElement: {
    marginTop: 18,
  },
  viewBlockAvatar: {
    marginTop: 13,
    height: 50,
    width: '100%',
    justifyContent: 'center',
  },
  viewBlockMember: {
    marginTop: 13,
    height: 50,
    width: '100%',
    justifyContent: 'center',
  },
  elementBlockAvatar: {
    height: 50,
    width: 50,
    padding: 2,
  },
  elementBlockAvatar1: {
    height: 50,
    width: 50,
    padding: 2,
    position: 'absolute',
    zIndex: 1,
  },
  title: {
    ...ApplicationStyles.fontMPLUS1pBold,
    fontSize: 13.5,
    color: Colors.black,
    marginTop: 20,
  },
  subTitle: {
    ...ApplicationStyles.fontMPLUS1pRegular,
    ...ApplicationStyles.paddingLeftInput,
    fontSize: 13.5,
    marginTop: 7,
    backgroundColor: Colors.white,
    borderColor: Colors.white,
    height: 40,
    color: Colors.black,
  },
  textArea: {
    ...ApplicationStyles.fontMPLUS1pRegular,
    ...ApplicationStyles.paddingLeftInput,
    fontSize: 13.5,
    marginTop: 7,
    backgroundColor: Colors.white,
    borderColor: Colors.white,
    height: width / 3.5,
    color: Colors.black,
  },
  textPlatinum: {
    fontSize: 12.5,
    ...ApplicationStyles.fontMPLUS1pMedium,
    color: Colors.gray5,
    marginBottom: -6,
  },
  textHistory: {
    fontSize: 12.5,
    ...ApplicationStyles.fontMPLUS1pMedium,
    color: Colors.gray5,
  },
  textBtnSignOut: {
    ...ApplicationStyles.fontMPLUS1pBold,
    fontSize: 13.5,
    marginRight: 5,
    color: Colors.white,
  },
  btnUpgrade: {
    height: 28,
    width: width / 5,
    backgroundColor: Colors.red,
    marginBottom: 10,
  },
  btnSeeAll: {
    color: Colors.red,
    fontSize: 12.5,
    ...ApplicationStyles.fontMPLUS1pMedium,
    marginLeft: 14,
    marginTop: 20,
  },
  btnSignOut: {
    backgroundColor: Colors.red,
    height: 40,
    width: width / 2.5,
    borderRadius: 10,
    marginTop: 36,
    alignItems: 'center',
    padding: 6,
  },
  btnModalYes: {
    flex: 1,
    alignItems: 'center',
    borderRightWidth: 0.5,
    paddingTop: 10,
    borderRightColor: Colors.gray5,
    height: 40,
  },
  btnModalCancel: {
    flex: 1,
    paddingTop: 10,
    alignItems: 'center',
    height: 40,
  },
  //style block member
  containerBlock: {
    position: 'absolute',
  },
  blockMember: {
    height: 50,
    width: 50,
    padding: 2,
    zIndex: 1,
    borderRadius: 25,
  },
  ViewButtonAdd: {
    height: 50,
    width: 50,
    borderRadius: 25,
    zIndex: 1,
    padding: 2,
  },
  viewImageAvatar: {
    height: 45,
    width: 45,
    borderRadius: 25,
    zIndex: 1,
    padding: 2,
  },
  btnAdd: {
    backgroundColor: '#DC3642',
    height: 45,
    width: 45,
    borderRadius: 25,
    zIndex: 1,
    alignItems: 'center',
  },
  titleButton: {
    fontSize: 11,
    fontFamily: 'MPLUS1p-Bold',
    color: 'white',
  },
  ViewButtonInvite: {
    backgroundColor: 'white',
    height: 50,
    width: 70,
    borderRadius: 25,
    position: 'absolute',
    zIndex: 2,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 2,
  },
  btnInvite: {
    backgroundColor: '#DC3642',
    height: 45,
    width: 65,
    borderRadius: 25,
    zIndex: 1,
    position: 'absolute',
    justifyContent: 'center',
    alignItems: 'center',
  },
});
